services:
  db:
    image: postgres:16.3
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changemeinprod!
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
